name: Delete tag and release
description: delete tag and release
author: "dev-drprasad"

branding:
  color: "red"
  icon: "delete"

inputs:
  tag_name:
    description: tag name
    required: true
  delete_release:
    description: whether to delete release or not
    required: false
    default: true
  owner:
    description: owner of the target repository
    required: false
  repo:
    description: target repository
    required: false

runs:
  using: "node12"
  main: "index.js"
